# Generated by Django 4.1.6 on 2023-05-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appointment_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='available', max_length=17),
        ),
    ]
